services:
  pipeline:
    build: .
    container_name: fairmarket_pipeline
    env_file:
      - .env
    volumes:
      - .:/app

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fairmarket_api
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    restart: unless-stopped